  File "manage.py", line 14
    ) from exc
         ^
SyntaxError: invalid syntax
[30/Oct/2020 07:54:55] "GET /index/ HTTP/1.1" 302 0
[30/Oct/2020 07:54:55] "GET /login/ HTTP/1.1" 200 2106
[30/Oct/2020 07:54:55] "GET /static/humane/themes/original.css HTTP/1.1" 200 1480
Performing system checks...

<pymysql.connections.Connection object at 0x7f7267e066a0>
System check identified no issues (0 silenced).

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
October 30, 2020 - 07:54:44
Django version 2.1.8, using settings 'mysite.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[30/Oct/2020 07:55:45] "GET /login/ HTTP/1.1" 200 2106
[30/Oct/2020 07:55:54] "POST /index/ HTTP/1.1" 200 7533
[30/Oct/2020 07:55:54] "GET /static/css/base.css HTTP/1.1" 304 0
[30/Oct/2020 07:55:54] "GET /static/css/index.css HTTP/1.1" 304 0
[30/Oct/2020 07:55:54] "GET /static/css/jquery.dialog.css HTTP/1.1" 304 0
[30/Oct/2020 07:55:54] "GET /static/js/core.js HTTP/1.1" 304 0
[30/Oct/2020 07:55:54] "GET /static/js/index.js HTTP/1.1" 304 0
[30/Oct/2020 07:55:54] "GET /static/js/jquery.dialog.js HTTP/1.1" 304 0
[30/Oct/2020 07:55:54] "GET /index/home.html HTTP/1.1" 200 14697
[30/Oct/2020 07:55:54] "GET /static/images/topbg.png HTTP/1.1" 200 27363
[30/Oct/2020 07:55:54] "GET /static/images/topuser.png HTTP/1.1" 200 21933
[30/Oct/2020 07:55:54] "GET /static/images/toplight.png HTTP/1.1" 200 26043
[30/Oct/2020 07:55:54] "GET /static/images/topline.png HTTP/1.1" 200 31448
[30/Oct/2020 07:55:54] "GET /static/images/LOGO74.png HTTP/1.1" 200 21563
[30/Oct/2020 07:55:54] "GET /static/js/layer_v2.1/layer/skin/layer.css HTTP/1.1" 200 15511
[30/Oct/2020 07:55:54] "GET /static/images/icon02.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:54] "GET /static/images/icon01.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:54] "GET /static/images/email03.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:54] "GET /static/images/icon04.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:54] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[30/Oct/2020 07:55:54] "GET /static/js/bootstrap-table.js HTTP/1.1" 304 0
[30/Oct/2020 07:55:54] "GET /static/js/common.js HTTP/1.1" 304 0
[30/Oct/2020 07:55:54] "GET /static/js/bootstrap-table-zh-CN.min.js HTTP/1.1" 304 0
[30/Oct/2020 07:55:55] "GET /static/css/home.css HTTP/1.1" 200 6231
[30/Oct/2020 07:55:55] "GET /static/css/bootstrap-table.css HTTP/1.1" 200 6956
[30/Oct/2020 07:55:55] "GET /static/images/righttitlebig.png HTTP/1.1" 200 21457
[30/Oct/2020 07:55:55] "GET /static/images/listico.png HTTP/1.1" 200 21442
[30/Oct/2020 07:55:55] "GET /static/images/titleico.png HTTP/1.1" 200 21661
[30/Oct/2020 07:55:55] "GET /static/images/more.png HTTP/1.1" 200 21439
[30/Oct/2020 07:55:55] "GET /static/images/topmail.png HTTP/1.1" 200 22244
[30/Oct/2020 07:55:55] "GET /static/images/countbg.png HTTP/1.1" 200 21503
[30/Oct/2020 07:55:55] "GET /static/images/home.png HTTP/1.1" 200 22827
[30/Oct/2020 07:55:55] "GET /static/images/icon03.png HTTP/1.1" 200 23946
[30/Oct/2020 07:55:56] "GET /static/images/exit.png HTTP/1.1" 200 22753
[30/Oct/2020 07:55:56] "GET /static/images/centertopbg.png HTTP/1.1" 200 21441
[30/Oct/2020 07:55:56] "GET /static/images/centerbottombg.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:56] "GET /static/images/lefttopbg.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:56] "GET /static/images/icon0.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:56] "GET /static/images/ico01.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:56] "GET /static/images/leftjt03.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:56] "GET /static/images/licon01.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:56] "GET /static/images/leftjt01.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:56] "GET /static/images/liicon06.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:56] "GET /static/images/ico06.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:56] "GET /static/images/liicon03.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:56] "GET /static/images/ico91.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:56] "GET /static/images/ico92.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:56] "GET /static/images/ico07.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:56] "GET /static/images/footbg.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:56] "GET /static/images/foot02.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:56] "GET /static/images/titlebg01.png HTTP/1.1" 200 21412
[30/Oct/2020 07:55:56] "GET /static/images/date.png HTTP/1.1" 200 25824
[30/Oct/2020 07:55:57] "GET /static/images/rmail.png HTTP/1.1" 200 21719
[30/Oct/2020 07:55:57] "GET /static/images/rmail1.png HTTP/1.1" 200 21664
[30/Oct/2020 07:55:57] "GET /static/images/datecion01.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:57] "GET /static/images/icon07.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:57] "GET /static/images/myFiles.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:57] "GET /static/images/icon09.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:57] "GET /static/images/add.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:57] "GET /static/images/dico.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:57] "GET /static/images/dialog_btnbg.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:58] "GET /static/images/leftjt02.png HTTP/1.1" 200 21522
[30/Oct/2020 07:55:58] "GET /static/images/leftjt04.png HTTP/1.1" 200 21422
[30/Oct/2020 07:55:58] "GET /index/absence.html HTTP/1.1" 200 9612
[30/Oct/2020 07:55:58] "GET /static/css/zTreeStyle/zTreeStyle.css HTTP/1.1" 200 6306
[30/Oct/2020 07:55:58] "GET /static/css/info-mgt.css HTTP/1.1" 304 0
[30/Oct/2020 07:55:59] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 122523
[30/Oct/2020 07:55:59] "GET /static/js/date/js/skins/molv/laydate.css HTTP/1.1" 304 0
[30/Oct/2020 07:55:59] "GET /static/js/date/js/skins/default/laydate.css HTTP/1.1" 200 3575
[30/Oct/2020 07:55:59] "GET /static/js/date/js/need/laydate.css HTTP/1.1" 200 5956
[30/Oct/2020 07:55:59] "GET /static/images/delico.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:59] "GET /static/images/toolbarbg.png HTTP/1.1" 304 0
[30/Oct/2020 07:55:59] "GET /index/work.html HTTP/1.1" 200 10313
[30/Oct/2020 07:56:01] "GET /index/schedule.html HTTP/1.1" 200 14053
[30/Oct/2020 07:56:01] "GET /static/images/addico.png HTTP/1.1" 200 21701
[30/Oct/2020 07:56:02] "GET /index/notice.html HTTP/1.1" 200 10122
[30/Oct/2020 07:56:03] "GET /index/schedule.html HTTP/1.1" 200 14053
[30/Oct/2020 07:56:20] "GET /index/home.html HTTP/1.1" 200 14697
[30/Oct/2020 07:56:27] "GET /index/home.html HTTP/1.1" 200 14697
[30/Oct/2020 07:56:29] "GET /index/classstatistics.html HTTP/1.1" 200 9842
[30/Oct/2020 07:56:44] "GET /index/home.html HTTP/1.1" 200 14697
[30/Oct/2020 07:56:47] "GET /index/calendar.html HTTP/1.1" 200 9804
[30/Oct/2020 07:56:47] "GET /static/js/layer_v2.1/layer/skin/default/icon.png HTTP/1.1" 200 11493
[30/Oct/2020 07:56:47] "GET /static/js/layer_v2.1/layer/skin/default/loading-0.gif HTTP/1.1" 200 5793
[30/Oct/2020 07:56:47] "GET /static/js/calendar/images/fontSize12.css HTTP/1.1" 200 181
[30/Oct/2020 07:56:47] "GET /static/js/calendar/images/skin.css HTTP/1.1" 200 1464
[30/Oct/2020 07:56:47] "GET /static/js/calendar/images/all.css HTTP/1.1" 200 3500
[30/Oct/2020 07:56:47] "GET /static/js/calendar/images/calendar.css HTTP/1.1" 200 2834
[30/Oct/2020 07:56:47] "GET /static/js/calendar/js/calendar.js HTTP/1.1" 200 42641
[30/Oct/2020 07:56:48] "GET /static/js/calendar/images/calTit.jpg HTTP/1.1" 200 10906
[30/Oct/2020 07:56:48] "GET /static/js/calendar/images/tool-sprites.gif HTTP/1.1" 200 4392
[30/Oct/2020 07:56:54] "GET /index/calendar.html HTTP/1.1" 200 9804
[30/Oct/2020 07:56:58] "GET /index/absence.html HTTP/1.1" 200 9612
[30/Oct/2020 07:56:58] "GET /static/css/zTreeStyle/zTreeStyle.css HTTP/1.1" 200 6306
[30/Oct/2020 07:56:58] "GET /static/js/work.js HTTP/1.1" 304 0
[30/Oct/2020 07:57:00] "GET /index/home.html HTTP/1.1" 200 14697
[30/Oct/2020 07:57:04] "GET /index/schedule.html HTTP/1.1" 200 14053
[30/Oct/2020 07:57:06] "GET /index/home.html HTTP/1.1" 200 14697
[30/Oct/2020 07:57:14] "GET /index/classstatistics.html HTTP/1.1" 200 9842
[30/Oct/2020 07:57:15] "GET /index/studentstatistics.html HTTP/1.1" 200 11886
[30/Oct/2020 07:57:28] "GET /index HTTP/1.1" 302 0
[30/Oct/2020 07:58:11] "GET /index/ HTTP/1.1" 302 0
[30/Oct/2020 07:58:11] "GET /login/ HTTP/1.1" 200 2106
[30/Oct/2020 07:58:11] "GET /static/humane/themes/original.css HTTP/1.1" 200 1480
[30/Oct/2020 07:58:11] "GET /static/css/login.css HTTP/1.1" 200 3789
[30/Oct/2020 07:58:11] "GET /static/humane/humane.js HTTP/1.1" 200 7078
[30/Oct/2020 07:58:11] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 200 92632
[30/Oct/2020 07:58:11] "GET /static/images/logo.png HTTP/1.1" 200 199830
[30/Oct/2020 07:58:15] "GET /static/images/login-bg.jpg HTTP/1.1" 200 413554
[30/Oct/2020 07:58:46] "GET /index/ HTTP/1.1" 200 2106
[30/Oct/2020 07:58:46] "GET /static/humane/humane.js HTTP/1.1" 304 0
[30/Oct/2020 07:58:46] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 304 0
[30/Oct/2020 07:58:46] "GET /static/humane/themes/original.css HTTP/1.1" 200 1480
[30/Oct/2020 07:58:47] "GET /static/css/login.css HTTP/1.1" 200 3789
[30/Oct/2020 07:58:47] "GET /static/images/login-bg.jpg HTTP/1.1" 304 0
[30/Oct/2020 07:58:47] "GET /static/images/logo.png HTTP/1.1" 200 199830
[30/Oct/2020 07:58:47] "GET /static/images/njit.png HTTP/1.1" 200 29837
[30/Oct/2020 07:58:53] "POST /index/ HTTP/1.1" 200 2109
[30/Oct/2020 07:59:01] "POST /index/ HTTP/1.1" 200 2109
[30/Oct/2020 07:59:06] "POST /index/ HTTP/1.1" 200 2109
[30/Oct/2020 07:59:09] "POST /index/ HTTP/1.1" 200 2109
[30/Oct/2020 07:59:12] "GET /index/ HTTP/1.1" 302 0
[30/Oct/2020 07:59:12] "GET /login/ HTTP/1.1" 200 2106
[30/Oct/2020 07:59:12] "GET /static/humane/themes/original.css HTTP/1.1" 200 1480
[30/Oct/2020 07:59:12] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 200 92632
[30/Oct/2020 07:59:12] "GET /static/humane/humane.js HTTP/1.1" 200 7078
[30/Oct/2020 07:59:12] "GET /static/css/login.css HTTP/1.1" 200 3789
[30/Oct/2020 07:59:13] "GET /static/images/logo.png HTTP/1.1" 200 199830
[30/Oct/2020 07:59:13] "POST /index/ HTTP/1.1" 200 2109
[30/Oct/2020 07:59:15] "GET /static/images/login-bg.jpg HTTP/1.1" 200 413554
[30/Oct/2020 08:00:00] "GET /index/ HTTP/1.1" 302 0
[30/Oct/2020 08:00:00] "GET /login/ HTTP/1.1" 200 2106
[30/Oct/2020 08:00:03] "POST /index/ HTTP/1.1" 200 2107
[30/Oct/2020 08:00:12] "POST /index/ HTTP/1.1" 200 7533
[30/Oct/2020 08:00:12] "GET /static/css/base.css HTTP/1.1" 200 8901
[30/Oct/2020 08:00:12] "GET /static/css/index.css HTTP/1.1" 200 7865
[30/Oct/2020 08:00:12] "GET /static/css/jquery.dialog.css HTTP/1.1" 200 2937
[30/Oct/2020 08:00:12] "GET /index/home.html HTTP/1.1" 200 14697
[30/Oct/2020 08:00:12] "GET /static/js/core.js HTTP/1.1" 200 35862
[30/Oct/2020 08:00:12] "GET /static/js/jquery.dialog.js HTTP/1.1" 200 13399
[30/Oct/2020 08:00:13] "GET /static/js/index.js HTTP/1.1" 200 3073
[30/Oct/2020 08:00:13] "GET /static/js/layer_v2.1/layer/layer.js HTTP/1.1" 200 20994
[30/Oct/2020 08:00:13] "GET /static/css/home.css HTTP/1.1" 200 6231
[30/Oct/2020 08:00:13] "GET /static/css/bootstrap-table.css HTTP/1.1" 200 6956
[30/Oct/2020 08:00:13] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 35951
[30/Oct/2020 08:00:13] "GET /static/js/bootstrap-table-zh-CN.min.js HTTP/1.1" 200 853
[30/Oct/2020 08:00:13] "GET /static/js/common.js HTTP/1.1" 200 3052
[30/Oct/2020 08:00:14] "GET /static/images/topbg.png HTTP/1.1" 200 27363
[30/Oct/2020 08:00:14] "GET /static/images/topline.png HTTP/1.1" 200 31448
[30/Oct/2020 08:00:15] "GET /static/js/bootstrap-table.js HTTP/1.1" 200 100271
[30/Oct/2020 08:00:15] "GET /static/images/toplight.png HTTP/1.1" 200 26043
[30/Oct/2020 08:00:15] "GET /static/images/LOGO74.png HTTP/1.1" 200 21563
[30/Oct/2020 08:00:16] "GET /static/images/topuser.png HTTP/1.1" 200 21933
[30/Oct/2020 08:00:16] "GET /static/images/topmail.png HTTP/1.1" 200 22244
[30/Oct/2020 08:00:16] "GET /static/images/countbg.png HTTP/1.1" 200 21503
[30/Oct/2020 08:00:16] "GET /static/images/home.png HTTP/1.1" 200 22827
[30/Oct/2020 08:00:17] "GET /static/images/icon03.png HTTP/1.1" 200 23946
[30/Oct/2020 08:00:17] "GET /static/images/exit.png HTTP/1.1" 200 22753
[30/Oct/2020 08:00:17] "GET /static/js/jquery.js HTTP/1.1" 200 294745
[30/Oct/2020 08:00:17] "GET /static/images/centertopbg.png HTTP/1.1" 200 21441
[30/Oct/2020 08:00:18] "GET /static/images/centerbottombg.png HTTP/1.1" 200 21435
[30/Oct/2020 08:00:18] "GET /static/images/lefttopbg.png HTTP/1.1" 200 22490
[30/Oct/2020 08:00:18] "GET /static/images/icon0.png HTTP/1.1" 200 21414
[30/Oct/2020 08:00:18] "GET /static/images/ico01.png HTTP/1.1" 200 22233
[30/Oct/2020 08:00:18] "GET /static/images/leftjt03.png HTTP/1.1" 200 21528
[30/Oct/2020 08:00:19] "GET /static/js/layer_v2.1/layer/skin/layer.css HTTP/1.1" 200 15511
[30/Oct/2020 08:00:19] "GET /static/images/licon01.png HTTP/1.1" 200 16639
[30/Oct/2020 08:00:19] "GET /static/images/leftjt01.png HTTP/1.1" 200 21570
[30/Oct/2020 08:00:19] "GET /static/images/liicon06.png HTTP/1.1" 200 21031
[30/Oct/2020 08:00:19] "GET /static/images/ico06.png HTTP/1.1" 200 22352
[30/Oct/2020 08:00:19] "GET /static/images/liicon03.png HTTP/1.1" 200 23195
[30/Oct/2020 08:00:20] "GET /static/images/ico91.png HTTP/1.1" 200 2188
[30/Oct/2020 08:00:20] "GET /static/images/ico92.png HTTP/1.1" 200 2238
[30/Oct/2020 08:00:20] "GET /static/images/footbg.png HTTP/1.1" 200 21425
[30/Oct/2020 08:00:20] "GET /static/images/ico07.png HTTP/1.1" 200 23047
[30/Oct/2020 08:00:20] "GET /static/images/foot02.png HTTP/1.1" 200 21426
[30/Oct/2020 08:00:20] "GET /static/images/dico.png HTTP/1.1" 200 24380
[30/Oct/2020 08:00:20] "GET /static/images/dialog_btnbg.png HTTP/1.1" 200 18938
[30/Oct/2020 08:00:20] "GET /static/images/dialogbtn.png HTTP/1.1" 200 18912
[30/Oct/2020 08:00:21] "GET /static/images/icon01.png HTTP/1.1" 200 23299
[30/Oct/2020 08:00:21] "GET /static/images/email03.png HTTP/1.1" 200 19077
[30/Oct/2020 08:00:21] "GET /static/images/icon02.png HTTP/1.1" 200 23054
[30/Oct/2020 08:00:21] "GET /static/images/icon04.png HTTP/1.1" 200 22171
[30/Oct/2020 08:00:21] "GET /static/images/icon07.png HTTP/1.1" 200 24436
[30/Oct/2020 08:00:21] "GET /static/images/myFiles.png HTTP/1.1" 200 21649
[30/Oct/2020 08:00:22] "GET /static/images/datecion01.png HTTP/1.1" 200 18669
[30/Oct/2020 08:00:22] "GET /static/images/icon09.png HTTP/1.1" 200 24095
[30/Oct/2020 08:00:22] "GET /static/images/add.png HTTP/1.1" 200 22040
[30/Oct/2020 08:00:22] "GET /static/images/righttitlebig.png HTTP/1.1" 200 21457
[30/Oct/2020 08:00:22] "GET /static/images/titleico.png HTTP/1.1" 200 21661
[30/Oct/2020 08:00:23] "GET /static/images/more.png HTTP/1.1" 200 21439
[30/Oct/2020 08:00:23] "GET /static/images/listico.png HTTP/1.1" 200 21442
[30/Oct/2020 08:00:23] "GET /static/images/titlebg01.png HTTP/1.1" 200 21412
[30/Oct/2020 08:00:23] "GET /static/images/date.png HTTP/1.1" 200 25824
[30/Oct/2020 08:00:23] "GET /static/images/rmail.png HTTP/1.1" 200 21719
[30/Oct/2020 08:00:23] "GET /static/images/rmail1.png HTTP/1.1" 200 21664
[30/Oct/2020 08:07:21] "GET /index/ HTTP/1.1" 302 0
[30/Oct/2020 08:07:21] "GET /login/ HTTP/1.1" 200 2106
[30/Oct/2020 08:07:21] "GET /static/humane/themes/original.css HTTP/1.1" 200 1480
[30/Oct/2020 08:07:21] "GET /static/humane/humane.js HTTP/1.1" 200 7078
[30/Oct/2020 08:07:21] "GET /static/css/login.css HTTP/1.1" 200 3789
[30/Oct/2020 08:07:22] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 200 92632
[30/Oct/2020 08:07:22] "GET /static/images/logo.png HTTP/1.1" 200 199830
[30/Oct/2020 08:07:26] "GET /static/images/login-bg.jpg HTTP/1.1" 200 413554
[30/Oct/2020 08:07:39] "POST /index/ HTTP/1.1" 200 7533
[30/Oct/2020 08:07:39] "GET /static/css/base.css HTTP/1.1" 200 8901
[30/Oct/2020 08:07:39] "GET /static/css/jquery.dialog.css HTTP/1.1" 200 2937
[30/Oct/2020 08:07:39] "GET /static/css/index.css HTTP/1.1" 200 7865
[30/Oct/2020 08:07:39] "GET /index/home.html HTTP/1.1" 200 14697
[30/Oct/2020 08:07:40] "GET /static/js/core.js HTTP/1.1" 200 35862
[30/Oct/2020 08:07:40] "GET /static/js/index.js HTTP/1.1" 200 3073
[30/Oct/2020 08:07:40] "GET /static/js/layer_v2.1/layer/layer.js HTTP/1.1" 200 20994
[30/Oct/2020 08:07:40] "GET /static/js/jquery.dialog.js HTTP/1.1" 200 13399
[30/Oct/2020 08:07:40] "GET /static/css/home.css HTTP/1.1" 200 6231
[30/Oct/2020 08:07:41] "GET /static/css/bootstrap-table.css HTTP/1.1" 200 6956
[30/Oct/2020 08:07:41] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 35951
[30/Oct/2020 08:07:41] "GET /static/js/bootstrap-table.js HTTP/1.1" 200 100271
[30/Oct/2020 08:07:43] "GET /static/js/jquery.js HTTP/1.1" 200 294745
[30/Oct/2020 08:07:44] "GET /static/js/bootstrap-table-zh-CN.min.js HTTP/1.1" 200 853
[30/Oct/2020 08:07:44] "GET /static/js/common.js HTTP/1.1" 200 3052
[30/Oct/2020 08:07:44] "GET /static/images/topline.png HTTP/1.1" 200 31448
[30/Oct/2020 08:07:44] "GET /static/js/layer_v2.1/layer/skin/layer.css HTTP/1.1" 200 15511
[30/Oct/2020 08:07:45] "GET /static/images/LOGO74.png HTTP/1.1" 200 21563
[30/Oct/2020 08:07:45] "GET /static/images/topmail.png HTTP/1.1" 200 22244
[30/Oct/2020 08:07:45] "GET /static/images/toplight.png HTTP/1.1" 200 26043
[30/Oct/2020 08:07:46] "GET /static/images/countbg.png HTTP/1.1" 200 21503
[30/Oct/2020 08:07:46] "GET /static/images/topuser.png HTTP/1.1" 200 21933
[30/Oct/2020 08:07:46] "GET /static/images/home.png HTTP/1.1" 200 22827
[30/Oct/2020 08:07:47] "GET /static/images/icon03.png HTTP/1.1" 200 23946
[30/Oct/2020 08:07:47] "GET /static/images/exit.png HTTP/1.1" 200 22753
[30/Oct/2020 08:07:47] "GET /static/images/centerbottombg.png HTTP/1.1" 200 21435
[30/Oct/2020 08:07:47] "GET /static/images/lefttopbg.png HTTP/1.1" 200 22490
[30/Oct/2020 08:07:48] "GET /static/images/topbg.png HTTP/1.1" 200 27363
[30/Oct/2020 08:07:48] "GET /static/images/icon0.png HTTP/1.1" 200 21414
[30/Oct/2020 08:07:48] "GET /static/images/ico01.png HTTP/1.1" 200 22233
[30/Oct/2020 08:07:48] "GET /static/images/centertopbg.png HTTP/1.1" 200 21441
[30/Oct/2020 08:07:48] "GET /static/images/leftjt03.png HTTP/1.1" 200 21528
[30/Oct/2020 08:07:48] "GET /static/images/licon01.png HTTP/1.1" 200 16639
[30/Oct/2020 08:07:48] "GET /static/images/liicon06.png HTTP/1.1" 200 21031
[30/Oct/2020 08:07:48] "GET /static/images/ico06.png HTTP/1.1" 200 22352
[30/Oct/2020 08:07:48] "GET /static/images/liicon03.png HTTP/1.1" 200 23195
[30/Oct/2020 08:07:49] "GET /static/images/leftjt01.png HTTP/1.1" 200 21570
[30/Oct/2020 08:07:49] "GET /static/images/ico91.png HTTP/1.1" 200 2188
[30/Oct/2020 08:07:49] "GET /static/images/ico92.png HTTP/1.1" 200 2238
[30/Oct/2020 08:07:49] "GET /static/images/ico07.png HTTP/1.1" 200 23047
[30/Oct/2020 08:07:49] "GET /static/images/footbg.png HTTP/1.1" 200 21425
[30/Oct/2020 08:07:49] "GET /static/images/foot02.png HTTP/1.1" 200 21426
[30/Oct/2020 08:07:49] "GET /static/images/dico.png HTTP/1.1" 200 24380
[30/Oct/2020 08:07:49] "GET /static/images/dialogbtn.png HTTP/1.1" 200 18912
[30/Oct/2020 08:07:50] "GET /static/images/icon01.png HTTP/1.1" 200 23299
[30/Oct/2020 08:07:50] "GET /static/images/email03.png HTTP/1.1" 200 19077
[30/Oct/2020 08:07:50] "GET /static/images/dialog_btnbg.png HTTP/1.1" 200 18938
[30/Oct/2020 08:07:50] "GET /static/images/icon04.png HTTP/1.1" 200 22171
[30/Oct/2020 08:07:50] "GET /static/images/datecion01.png HTTP/1.1" 200 18669
[30/Oct/2020 08:07:50] "GET /static/images/icon07.png HTTP/1.1" 200 24436
[30/Oct/2020 08:07:51] "GET /static/images/icon02.png HTTP/1.1" 200 23054
[30/Oct/2020 08:07:51] "GET /static/images/myFiles.png HTTP/1.1" 200 21649
[30/Oct/2020 08:07:51] "GET /static/images/righttitlebig.png HTTP/1.1" 200 21457
[30/Oct/2020 08:07:51] "GET /static/images/titleico.png HTTP/1.1" 200 21661
[30/Oct/2020 08:07:51] "GET /static/images/more.png HTTP/1.1" 200 21439
[30/Oct/2020 08:07:52] "GET /static/images/listico.png HTTP/1.1" 200 21442
[30/Oct/2020 08:07:52] "GET /static/images/icon09.png HTTP/1.1" 200 24095
[30/Oct/2020 08:07:52] "GET /static/images/titlebg01.png HTTP/1.1" 200 21412
[30/Oct/2020 08:07:52] "GET /static/images/rmail.png HTTP/1.1" 200 21719
[30/Oct/2020 08:07:52] "GET /static/images/add.png HTTP/1.1" 200 22040
[30/Oct/2020 08:07:54] "GET /static/images/date.png HTTP/1.1" 200 25824
[30/Oct/2020 08:07:54] "GET /static/images/rmail1.png HTTP/1.1" 200 21664
[30/Oct/2020 08:12:14] "GET /login HTTP/1.1" 302 0
[30/Oct/2020 08:12:20] "GET /login/ HTTP/1.1" 200 2106
[30/Oct/2020 08:12:47] "GET /static/humane/humane.js HTTP/1.1" 200 7078
[30/Oct/2020 08:13:08] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 200 92632
[30/Oct/2020 08:24:12] "GET /index/ HTTP/1.1" 200 2106
[30/Oct/2020 08:24:12] "GET /static/humane/themes/original.css HTTP/1.1" 304 0
[30/Oct/2020 08:24:12] "GET /static/css/login.css HTTP/1.1" 304 0
[30/Oct/2020 08:24:12] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 304 0
[30/Oct/2020 08:24:12] "GET /static/humane/humane.js HTTP/1.1" 304 0
[30/Oct/2020 08:24:12] "GET /static/images/logo.png HTTP/1.1" 304 0
[30/Oct/2020 08:24:13] "GET /static/images/login-bg.jpg HTTP/1.1" 304 0
[30/Oct/2020 08:31:36] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[30/Oct/2020 09:18:14] "GET /index HTTP/1.1" 302 0
[30/Oct/2020 09:18:19] "GET /login/ HTTP/1.1" 200 2106
[30/Oct/2020 09:18:47] "GET /static/humane/humane.js HTTP/1.1" 200 7078
[30/Oct/2020 09:19:07] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 200 92632
[30/Oct/2020 09:49:46] "GET /index/ HTTP/1.1" 302 0
[30/Oct/2020 09:49:46] "GET /login/ HTTP/1.1" 200 2106
[30/Oct/2020 09:49:46] "GET /static/humane/themes/original.css HTTP/1.1" 200 1480
[30/Oct/2020 09:49:46] "GET /static/css/login.css HTTP/1.1" 304 0
[30/Oct/2020 09:49:46] "GET /static/humane/humane.js HTTP/1.1" 304 0
[30/Oct/2020 09:49:46] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 304 0
[30/Oct/2020 09:49:46] "GET /static/images/logo.png HTTP/1.1" 304 0
[30/Oct/2020 09:49:46] "GET /static/images/login-bg.jpg HTTP/1.1" 304 0
[30/Oct/2020 09:49:46] "GET /static/images/njit.png HTTP/1.1" 200 29837
[30/Oct/2020 09:50:08] "POST /index/ HTTP/1.1" 200 7535
[30/Oct/2020 09:50:08] "GET /static/css/base.css HTTP/1.1" 304 0
[30/Oct/2020 09:50:08] "GET /static/css/jquery.dialog.css HTTP/1.1" 304 0
[30/Oct/2020 09:50:08] "GET /static/css/index.css HTTP/1.1" 304 0
[30/Oct/2020 09:50:08] "GET /static/js/jquery.dialog.js HTTP/1.1" 304 0
[30/Oct/2020 09:50:08] "GET /static/js/jquery.js HTTP/1.1" 304 0
[30/Oct/2020 09:50:08] "GET /static/js/core.js HTTP/1.1" 304 0
[30/Oct/2020 09:50:08] "GET /static/js/index.js HTTP/1.1" 304 0
[30/Oct/2020 09:50:08] "GET /static/js/layer_v2.1/layer/layer.js HTTP/1.1" 304 0
[30/Oct/2020 09:50:08] "GET /index/home.html HTTP/1.1" 200 14697
[30/Oct/2020 09:50:08] "GET /static/images/topbg.png HTTP/1.1" 200 27363
[30/Oct/2020 09:50:08] "GET /static/images/topline.png HTTP/1.1" 200 31448
[30/Oct/2020 09:50:08] "GET /static/images/toplight.png HTTP/1.1" 200 26043
[30/Oct/2020 09:50:08] "GET /static/images/LOGO74.png HTTP/1.1" 200 21563
[30/Oct/2020 09:50:08] "GET /static/images/topuser.png HTTP/1.1" 200 21933
[30/Oct/2020 09:50:08] "GET /static/images/topmail.png HTTP/1.1" 200 22244
[30/Oct/2020 09:50:08] "GET /static/images/countbg.png HTTP/1.1" 200 21503
[30/Oct/2020 09:50:08] "GET /static/images/home.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:08] "GET /static/images/icon03.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:09] "GET /static/images/exit.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:09] "GET /static/images/centertopbg.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:09] "GET /static/images/centerbottombg.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:09] "GET /static/js/layer_v2.1/layer/skin/layer.css HTTP/1.1" 200 15511
[30/Oct/2020 09:50:09] "GET /static/css/home.css HTTP/1.1" 200 6231
[30/Oct/2020 09:50:09] "GET /static/css/bootstrap-table.css HTTP/1.1" 200 6956
[30/Oct/2020 09:50:09] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[30/Oct/2020 09:50:09] "GET /static/js/bootstrap-table.js HTTP/1.1" 304 0
[30/Oct/2020 09:50:09] "GET /static/js/bootstrap-table-zh-CN.min.js HTTP/1.1" 304 0
[30/Oct/2020 09:50:09] "GET /static/js/common.js HTTP/1.1" 304 0
[30/Oct/2020 09:50:09] "GET /static/images/righttitlebig.png HTTP/1.1" 200 21457
[30/Oct/2020 09:50:09] "GET /static/images/titleico.png HTTP/1.1" 200 21661
[30/Oct/2020 09:50:10] "GET /static/images/lefttopbg.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/icon0.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/ico01.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/leftjt03.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/licon01.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/leftjt01.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/liicon06.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/ico06.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/liicon03.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/ico91.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/ico92.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/ico07.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/footbg.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/foot02.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/dico.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/dialog_btnbg.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/dialogbtn.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/more.png HTTP/1.1" 200 21439
[30/Oct/2020 09:50:10] "GET /static/images/listico.png HTTP/1.1" 200 21442
[30/Oct/2020 09:50:10] "GET /static/images/titlebg01.png HTTP/1.1" 200 21412
[30/Oct/2020 09:50:10] "GET /static/images/date.png HTTP/1.1" 200 25824
[30/Oct/2020 09:50:10] "GET /static/images/rmail.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/rmail1.png HTTP/1.1" 304 0
[30/Oct/2020 09:50:10] "GET /static/images/icon01.png HTTP/1.1" 200 23299
[30/Oct/2020 09:50:10] "GET /static/images/email03.png HTTP/1.1" 200 19077
[30/Oct/2020 09:50:10] "GET /static/images/icon02.png HTTP/1.1" 200 23054
[30/Oct/2020 09:50:10] "GET /static/images/icon04.png HTTP/1.1" 200 22171
[30/Oct/2020 09:50:10] "GET /static/images/datecion01.png HTTP/1.1" 200 18669
[30/Oct/2020 09:50:10] "GET /static/images/icon07.png HTTP/1.1" 200 24436
[30/Oct/2020 09:50:11] "GET /static/images/myFiles.png HTTP/1.1" 200 21649
[30/Oct/2020 09:50:11] "GET /static/images/icon09.png HTTP/1.1" 200 24095
[30/Oct/2020 09:50:11] "GET /static/images/add.png HTTP/1.1" 200 22040
[30/Oct/2020 09:50:16] "GET /static/images/leftjt02.png HTTP/1.1" 200 21522
[30/Oct/2020 09:50:16] "GET /static/images/leftjt04.png HTTP/1.1" 200 21422
[30/Oct/2020 09:50:25] "GET /index/home.html HTTP/1.1" 200 14697
[30/Oct/2020 09:50:26] "GET /index/home.html HTTP/1.1" 200 14697
[30/Oct/2020 09:50:59] "GET /index/notice.html HTTP/1.1" 200 10122
[30/Oct/2020 09:50:59] "GET /static/css/zTreeStyle/zTreeStyle.css HTTP/1.1" 200 6306
[30/Oct/2020 09:50:59] "GET /static/css/info-mgt.css HTTP/1.1" 200 1678
[30/Oct/2020 09:50:59] "GET /static/js/page.js HTTP/1.1" 200 505
[30/Oct/2020 09:50:59] "GET /static/js/date/js/laydate.js HTTP/1.1" 304 0
[30/Oct/2020 09:50:59] "GET /static/js/work.js HTTP/1.1" 304 0
[30/Oct/2020 09:50:59] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 122523
[30/Oct/2020 09:50:59] "GET /static/images/toolbarbg.png HTTP/1.1" 200 21424
[30/Oct/2020 09:50:59] "GET /static/images/delico.png HTTP/1.1" 200 21885
[30/Oct/2020 09:50:59] "GET /static/js/date/js/need/laydate.css HTTP/1.1" 200 5956
[30/Oct/2020 09:50:59] "GET /static/js/date/js/skins/default/laydate.css HTTP/1.1" 200 3575
[30/Oct/2020 09:50:59] "GET /static/js/date/js/skins/molv/laydate.css HTTP/1.1" 200 3549
[30/Oct/2020 09:51:20] "GET /static/js/layer_v2.1/layer/skin/default/icon.png HTTP/1.1" 200 11493
[30/Oct/2020 09:51:20] "GET /static/js/layer_v2.1/layer/skin/default/loading-0.gif HTTP/1.1" 200 5793
[30/Oct/2020 09:51:20] "GET /index/calendar.html HTTP/1.1" 200 9804
[30/Oct/2020 09:51:20] "GET /static/js/calendar/images/all.css HTTP/1.1" 200 3500
[30/Oct/2020 09:51:20] "GET /static/js/calendar/images/skin.css HTTP/1.1" 200 1464
[30/Oct/2020 09:51:20] "GET /static/js/calendar/images/fontSize12.css HTTP/1.1" 200 181
[30/Oct/2020 09:51:20] "GET /static/js/calendar/images/calendar.css HTTP/1.1" 200 2834
[30/Oct/2020 09:51:20] "GET /static/js/calendar/js/calendar.js HTTP/1.1" 304 0
[30/Oct/2020 09:51:20] "GET /static/js/calendar/images/calTit.jpg HTTP/1.1" 200 10906
[30/Oct/2020 09:51:20] "GET /static/js/calendar/images/tool-sprites.gif HTTP/1.1" 200 4392
[30/Oct/2020 09:52:53] "GET /index/absence.html HTTP/1.1" 200 9612
[30/Oct/2020 09:52:54] "GET /index/notice.html HTTP/1.1" 200 10122
[30/Oct/2020 09:52:56] "GET /index/absence.html HTTP/1.1" 200 9612
[30/Oct/2020 09:52:57] "GET /index/notice.html HTTP/1.1" 200 10122
[30/Oct/2020 09:52:57] "GET /index/absence.html HTTP/1.1" 200 9612
[30/Oct/2020 09:52:59] "GET /index/notice.html HTTP/1.1" 200 10122
[30/Oct/2020 09:53:01] "GET /index/notice.html HTTP/1.1" 200 10122
[30/Oct/2020 09:53:02] "GET /index/notice.html HTTP/1.1" 200 10122
[30/Oct/2020 09:53:02] "GET /index/absence.html HTTP/1.1" 200 9612
[30/Oct/2020 09:53:09] "GET /index/notice.html HTTP/1.1" 200 10122
[30/Oct/2020 09:53:11] "GET /index/absence.html HTTP/1.1" 200 9612
[30/Oct/2020 09:53:15] "GET /index/schedule.html HTTP/1.1" 200 14053
[30/Oct/2020 09:53:15] "GET /static/images/addico.png HTTP/1.1" 200 21701
[30/Oct/2020 09:53:15] "GET /index/curriculum.html HTTP/1.1" 200 15738
[30/Oct/2020 09:53:16] "GET /static/images/edtico.png HTTP/1.1" 200 21577
[30/Oct/2020 09:53:18] "GET /index/schedule.html HTTP/1.1" 200 14053
[30/Oct/2020 09:53:19] "GET /index/curriculum.html HTTP/1.1" 200 15738
[30/Oct/2020 09:53:27] "GET /index/curriculum_add HTTP/1.1" 200 12404
[30/Oct/2020 09:53:27] "GET /static/css/tail.css HTTP/1.1" 200 1496
[30/Oct/2020 09:53:27] "GET /static/js/date/js/need/laydate.css HTTP/1.1" 200 5956
[30/Oct/2020 09:53:29] "GET /index/curriculum.html HTTP/1.1" 200 15738
[30/Oct/2020 09:53:29] "GET /static/js/jquery.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:29] "GET /static/js/page.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:29] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:29] "GET /static/js/date/js/laydate.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:29] "GET /static/js/bootstrap-table-zh-CN.min.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:29] "GET /static/js/bootstrap-table.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:29] "GET /static/js/work.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:29] "GET /static/js/layer_v2.1/layer/layer.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:29] "GET /static/js/jquery.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:29] "GET /index/curriculum_tail?id=14 HTTP/1.1" 200 12580
[30/Oct/2020 09:53:31] "GET /index/curriculum.html HTTP/1.1" 200 15738
[30/Oct/2020 09:53:31] "GET /static/js/jquery.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:31] "GET /static/js/date/js/laydate.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:31] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:31] "GET /static/js/page.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:31] "GET /static/js/bootstrap-table-zh-CN.min.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:31] "GET /static/js/bootstrap-table.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:31] "GET /static/js/layer_v2.1/layer/layer.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:31] "GET /static/js/work.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:31] "GET /static/js/jquery.js HTTP/1.1" 304 0
[30/Oct/2020 09:53:59] "GET /index/curriculum_tail?id=14 HTTP/1.1" 200 12580
[30/Oct/2020 09:54:09] "GET /index/curriculum.html HTTP/1.1" 200 15738
[30/Oct/2020 09:54:09] "GET /static/js/jquery.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:09] "GET /static/js/page.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:09] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:09] "GET /static/js/bootstrap-table.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:09] "GET /static/js/bootstrap-table-zh-CN.min.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:10] "GET /static/js/date/js/laydate.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:10] "GET /static/js/work.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:10] "GET /static/js/layer_v2.1/layer/layer.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:10] "GET /static/js/jquery.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:11] "GET /index/curriculum_tail?id=38 HTTP/1.1" 200 12577
[30/Oct/2020 09:54:13] "GET /index/curriculum.html HTTP/1.1" 200 15738
[30/Oct/2020 09:54:13] "GET /static/js/jquery.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:13] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:13] "GET /static/js/page.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:13] "GET /static/js/bootstrap-table-zh-CN.min.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:13] "GET /static/js/bootstrap-table.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:13] "GET /static/js/date/js/laydate.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:13] "GET /static/js/work.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:13] "GET /static/js/layer_v2.1/layer/layer.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:13] "GET /static/js/jquery.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:16] "GET /index/schedule.html HTTP/1.1" 200 14053
[30/Oct/2020 09:54:17] "GET /index/getKecheng?id=2141509&term=1&year=1 HTTP/1.1" 200 976
[30/Oct/2020 09:54:21] "GET /index/getKecheng?id=2141510&term=1&year=1 HTTP/1.1" 200 641
[30/Oct/2020 09:54:26] "GET /index/subject.html HTTP/1.1" 200 9353
[30/Oct/2020 09:54:26] "GET /static/css/jquery.treetable.css HTTP/1.1" 200 652
[30/Oct/2020 09:54:26] "GET /static/css/jquery.treetable.theme.default.css HTTP/1.1" 200 29773
[30/Oct/2020 09:54:26] "GET /static/js/jquery.treetable.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:26] "GET /index/class.html HTTP/1.1" 200 9293
[30/Oct/2020 09:54:30] "GET /index/updateclass?id=2011513 HTTP/1.1" 200 3625
Not Found: /index/{% static 'js/jquery.js
[30/Oct/2020 09:54:30] "GET /index/%7B%%20static%20'js/jquery.js HTTP/1.1" 404 9344
Not Found: /index/images/start.png
[30/Oct/2020 09:54:30] "GET /index/images/start.png HTTP/1.1" 404 9303
[30/Oct/2020 09:54:31] "GET /index/class.html HTTP/1.1" 200 9293
[30/Oct/2020 09:54:31] "GET /static/js/jquery.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:31] "GET /static/js/page.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:31] "GET /static/js/jquery.treetable.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:31] "GET /static/js/layer_v2.1/layer/layer.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:32] "GET /index/updateclass?id=2011514 HTTP/1.1" 200 3625
Not Found: /index/{% static 'js/jquery.js
[30/Oct/2020 09:54:32] "GET /index/%7B%%20static%20'js/jquery.js HTTP/1.1" 404 9344
Not Found: /index/images/start.png
[30/Oct/2020 09:54:33] "GET /index/images/start.png HTTP/1.1" 404 9303
[30/Oct/2020 09:54:34] "GET /index/class.html HTTP/1.1" 200 9293
[30/Oct/2020 09:54:34] "GET /static/js/page.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:34] "GET /static/js/jquery.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:34] "GET /static/js/jquery.treetable.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:34] "GET /static/js/layer_v2.1/layer/layer.js HTTP/1.1" 304 0
[30/Oct/2020 09:54:48] "POST /index/class.html HTTP/1.1" 200 6849
[30/Oct/2020 09:54:53] "GET /index/updateclass?id=2081501 HTTP/1.1" 200 3625
Not Found: /index/{% static 'js/jquery.js
[30/Oct/2020 09:54:54] "GET /index/%7B%%20static%20'js/jquery.js HTTP/1.1" 404 9344
Not Found: /index/images/start.png
[30/Oct/2020 09:54:54] "GET /index/images/start.png HTTP/1.1" 404 9303
[30/Oct/2020 09:55:02] "GET /index/subject.html HTTP/1.1" 200 9353
[30/Oct/2020 09:55:04] "GET /index/teacher.html HTTP/1.1" 200 12609
[30/Oct/2020 09:55:05] "GET /static/js/date/js/skins/danlan/laydate.css HTTP/1.1" 200 3427
[30/Oct/2020 09:55:05] "GET /index/student.html HTTP/1.1" 200 16605
[30/Oct/2020 09:55:07] "GET /index/class.html HTTP/1.1" 200 9293
[30/Oct/2020 09:55:25] "GET /index/subject.html HTTP/1.1" 200 9353
[30/Oct/2020 09:55:27] "GET /index/behavior.html HTTP/1.1" 200 7817
[30/Oct/2020 09:55:35] "GET /index/updatebehavior?id=1 HTTP/1.1" 200 3838
Not Found: /index/{% static 'js/jquery.js
[30/Oct/2020 09:55:35] "GET /index/%7B%%20static%20'js/jquery.js HTTP/1.1" 404 9344
Not Found: /index/images/start.png
[30/Oct/2020 09:55:35] "GET /index/images/start.png HTTP/1.1" 404 9303
[30/Oct/2020 09:55:36] "GET /index/behavior.html HTTP/1.1" 200 7817
[30/Oct/2020 09:55:37] "GET /static/js/jquery.treetable.js HTTP/1.1" 304 0
[30/Oct/2020 09:55:37] "GET /static/js/jquery.js HTTP/1.1" 304 0
[30/Oct/2020 09:55:37] "GET /static/js/page.js HTTP/1.1" 304 0
[30/Oct/2020 09:55:37] "GET /static/js/layer_v2.1/layer/layer.js HTTP/1.1" 304 0
[30/Oct/2020 09:55:44] "GET /static/images/lefttop.png HTTP/1.1" 200 19047
[30/Oct/2020 09:55:44] "GET /static/images/righttop.png HTTP/1.1" 200 19072
[30/Oct/2020 09:55:44] "GET /static/images/close3.png HTTP/1.1" 200 18957
[30/Oct/2020 09:55:44] "GET /static/images/topcenter.png HTTP/1.1" 200 18947
[30/Oct/2020 09:55:44] "GET /static/images/centerleft.png HTTP/1.1" 200 18918
[30/Oct/2020 09:55:44] "GET /static/images/centerright.png HTTP/1.1" 200 18916
[30/Oct/2020 09:55:44] "GET /static/images/downcenter.png HTTP/1.1" 200 18932
[30/Oct/2020 09:55:45] "GET /index/login.html HTTP/1.1" 200 2098
[30/Oct/2020 09:55:45] "GET /static/images/njit.png HTTP/1.1" 200 29837
[30/Oct/2020 09:55:45] "GET /static/images/logo.png HTTP/1.1" 200 90112
[30/Oct/2020 09:55:56] "POST /index/ HTTP/1.1" 200 2109
[30/Oct/2020 09:56:02] "POST /index/ HTTP/1.1" 200 2109
[30/Oct/2020 09:56:02] "GET /static/humane/humane.js HTTP/1.1" 304 0
[30/Oct/2020 09:56:02] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 304 0
[30/Oct/2020 09:56:02] "GET /static/images/logo.png HTTP/1.1" 304 0
[30/Oct/2020 09:56:05] "GET /index/ HTTP/1.1" 302 0
[30/Oct/2020 09:56:05] "GET /login/ HTTP/1.1" 200 2106
[30/Oct/2020 13:09:16] "GET /index/ HTTP/1.1" 302 0
[30/Oct/2020 13:09:16] "GET /login/ HTTP/1.1" 200 2106
[30/Oct/2020 13:09:16] "GET /static/humane/themes/original.css HTTP/1.1" 304 0
[30/Oct/2020 13:09:16] "GET /static/css/login.css HTTP/1.1" 304 0
[30/Oct/2020 13:09:16] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 304 0
[30/Oct/2020 13:09:16] "GET /static/images/logo.png HTTP/1.1" 304 0
[30/Oct/2020 13:09:16] "GET /static/humane/humane.js HTTP/1.1" 304 0
[30/Oct/2020 13:09:16] "GET /static/images/login-bg.jpg HTTP/1.1" 304 0
[30/Oct/2020 13:17:08] "GET /index/ HTTP/1.1" 302 0
[30/Oct/2020 13:17:08] "GET /login/ HTTP/1.1" 200 2106
[30/Oct/2020 13:17:08] "GET /static/humane/themes/original.css HTTP/1.1" 200 1480
[30/Oct/2020 13:17:08] "GET /static/humane/humane.js HTTP/1.1" 200 7078
[30/Oct/2020 13:17:08] "GET /static/css/login.css HTTP/1.1" 200 3789
[30/Oct/2020 13:17:08] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 200 90112
[30/Oct/2020 13:17:10] "GET /login/ HTTP/1.1" 200 2106
[30/Oct/2020 13:17:10] "GET /static/humane/themes/original.css HTTP/1.1" 200 1480
[30/Oct/2020 13:17:10] "GET /static/humane/humane.js HTTP/1.1" 200 7078
[30/Oct/2020 13:17:10] "GET /static/css/login.css HTTP/1.1" 200 3789
[30/Oct/2020 13:17:10] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 200 92632
[30/Oct/2020 13:17:10] "GET /static/images/logo.png HTTP/1.1" 200 199830
[30/Oct/2020 13:17:13] "GET /static/images/login-bg.jpg HTTP/1.1" 200 413554
[30/Oct/2020 13:18:05] "GET / HTTP/1.0" 302 0
[30/Oct/2020 13:18:14] "GET /login/ HTTP/1.0" 200 2106
[30/Oct/2020 13:29:04] "GET /index HTTP/1.1" 302 0
[30/Oct/2020 13:46:17] "GET /index/ HTTP/1.1" 302 0
[30/Oct/2020 13:46:17] "GET /login/ HTTP/1.1" 200 2106
[30/Oct/2020 13:46:17] "GET /static/humane/themes/original.css HTTP/1.1" 200 1480
[30/Oct/2020 13:46:17] "GET /static/css/login.css HTTP/1.1" 200 3789
[30/Oct/2020 13:46:17] "GET /static/humane/humane.js HTTP/1.1" 200 7078
[30/Oct/2020 13:46:18] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 200 92632
[30/Oct/2020 13:46:18] "GET /static/images/logo.png HTTP/1.1" 200 199830
[30/Oct/2020 13:46:23] "GET /login/ HTTP/1.1" 200 2106
[30/Oct/2020 13:46:23] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 200 92632
[30/Oct/2020 13:46:24] "GET /static/images/logo.png HTTP/1.1" 200 199830
[30/Oct/2020 13:46:27] "GET /static/images/login-bg.jpg HTTP/1.1" 200 413554
[30/Oct/2020 13:46:28] "GET /static/images/njit.png HTTP/1.1" 200 29837
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[30/Oct/2020 13:58:27] "GET /login HTTP/1.1" 302 0
[30/Oct/2020 15:44:22] "GET / HTTP/1.0" 302 0
[30/Oct/2020 15:44:23] "GET /login/ HTTP/1.0" 200 2106
[30/Oct/2020 16:49:50] "GET / HTTP/1.1" 302 0
[30/Oct/2020 18:05:24] "GET / HTTP/1.1" 302 0
[30/Oct/2020 18:05:24] "GET / HTTP/1.0" 302 0
[30/Oct/2020 18:05:24] code 400, message Bad HTTP/0.9 request type ('\x80\x80\x01\x03\x01\x00W\x00\x00\x00')
[30/Oct/2020 18:05:24] " W          " 400 -
[30/Oct/2020 18:05:24] code 400, message Bad request syntax ('\x00\x00\x00àZ\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x05\x01=K\x00\x00\x01\x01gÄ\x13')
[30/Oct/2020 18:05:24] "   àZ          =K  gÄ" 400 -
[30/Oct/2020 18:05:24] code 400, message Bad request syntax ('\x03\x00\x00\x16\x11à\x00\x00\x00\x04\x00Á\x02\x01\x00Â\x02\x01\x02À\x01')
[30/Oct/2020 18:05:24] "  à    Á ÂÀ" 400 -
[30/Oct/2020 18:05:24] code 400, message Bad request version ('\x00/\x00')
[30/Oct/2020 18:05:24] You're accessing the development server over HTTPS, but it only supports HTTP.

[30/Oct/2020 18:05:24] code 400, message Bad request version ('SIP/2.0')
[30/Oct/2020 18:05:24] "OPTIONS sip:nm SIP/2.0" 400 -
[30/Oct/2020 18:05:24] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00*%à\x00\x00\x00\x00\x00Cookie:')
[30/Oct/2020 18:05:24] "  *%à     Cookie: mstshash=root" 400 -
[30/Oct/2020 18:05:24] code 400, message Bad request syntax ('A\x00\x00\x00:0\x00\x00ÿÿÿÿÔ\x07\x00\x00\x00\x00\x00\x00test.$cmd\x00\x00\x00\x00\x00ÿÿÿÿ\x1b\x00\x00\x00\x01serverStatus\x00\x00\x00\x00\x00\x00\x00ð?\x00')
[30/Oct/2020 18:05:24] "A   :0  ÿÿÿÿÔ      test.$cmd     ÿÿÿÿ   serverStatus       ð? " 400 -
[30/Oct/2020 18:05:24] code 400, message Bad request syntax ('\x00\x00\x00¤ÿSMBr\x00\x00\x00\x00\x08\x01@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x06\x00\x00\x01\x00\x00\x81\x00\x02PC NETWORK PROGRAM 1.0\x00\x02MICROSOFT NETWORKS 1.03\x00\x02MICROSOFT NETWORKS 3.0\x00\x02LANMAN1.0\x00\x02LM1.2X002\x00\x02Samba\x00\x02NT LANMAN 1.0\x00\x02NT LM 0.12\x00')
[30/Oct/2020 18:05:24] "   ¤ÿSMBr    @              @     PC NETWORK PROGRAM 1.0 MICROSOFT NETWORKS 1.03 MICROSOFT NETWORKS 3.0 LANMAN1.0 LM1.2X002 Samba NT LANMAN 1.0 NT LM 0.12 " 400 -
[30/Oct/2020 18:05:24] code 400, message Bad request syntax ('\x00¦\x00\x00\x01\x00\x00\x00\x014\x01,\x00\x00\x08\x00\x7fÿO\x98\x00\x00\x00\x01\x00\x84\x00"\x00\x00\x00\x00\x01\x01(DESCRIPTION=(CONNECT_DATA=(SID=test)(CID=(PROGRAM=)(HOST=__jdbc__)(USER=)))(ADDRESS=(PROTOCOL=tcp)(HOST=162.27.59.135)(PORT=1521)))')
[30/Oct/2020 18:05:24] " ¦     4,   ÿO     "    (DESCRIPTION=(CONNECT_DATA=(SID=test)(CID=(PROGRAM=)(HOST=__jdbc__)(USER=)))(ADDRESS=(PROTOCOL=tcp)(HOST=162.27.59.135)(PORT=1521)))" 400 -
[30/Oct/2020 18:05:24] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00')
[30/Oct/2020 18:05:24] "  à     " 400 -
[30/Oct/2020 18:05:24] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00')
[30/Oct/2020 18:05:24] "  à     " 400 -
[30/Oct/2020 18:05:24] code 400, message Bad HTTP/0.9 request type ('\x05\x00`\x00\x00\x00\x00ãÅ(ýJT#')
[30/Oct/2020 18:05:24] "  `    ãÅ(ýJT#	pdúU$   ¡ª" 400 -
[30/Oct/2020 18:05:24] code 400, message Bad request version ('\x03\x00(\x00\x04ÿ\x08\x00\x00Â\x00\x00\x00MSSQLServer\x00¬\x07\x00\x00')
[30/Oct/2020 18:05:24] " 4            ( ÿ  Â   MSSQLServer ¬  " 400 -
[30/Oct/2020 18:05:24] code 400, message Bad request version ('GetClassName\x00\x00\x00\x02\x04\x00\x00\x00\x00\x01\x00')
[30/Oct/2020 18:05:24] "          GetClassName        " 400 -
[30/Oct/2020 18:11:30] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x01"\x01\x00\x01')
[30/Oct/2020 18:11:30] You're accessing the development server over HTTPS, but it only supports HTTP.

[30/Oct/2020 18:11:30] code 400, message Bad request syntax ('\x16\x03\x01\x01"\x01\x00\x01\x1e\x03\x03Ø\x11}i[.Ã\x1e\x0cÚ\x909\x0eEä¹\x1awV$Ñ\x00&ðTøªíèå\x80\r\x00\x00\x88À0À,À(À$À\x14À')
[30/Oct/2020 18:11:30] You're accessing the development server over HTTPS, but it only supports HTTP.

[30/Oct/2020 18:11:30] code 400, message Bad HTTP/0.9 request type ("\x16\x03\x01\x00Æ\x01\x00\x00Â\x03\x02^bp®÷g½íõÜãN\x10'PÏ0")
[30/Oct/2020 18:11:30] You're accessing the development server over HTTPS, but it only supports HTTP.

[30/Oct/2020 18:11:31] code 400, message Bad request version ('¸\x9a\x00\x00PÀ\x14À')
[30/Oct/2020 18:11:31] You're accessing the development server over HTTPS, but it only supports HTTP.

[30/Oct/2020 18:11:31] "GET / HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[30/Oct/2020 18:18:42] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[30/Oct/2020 22:15:25] "GET http://www.qq.com/404/search_children.js HTTP/1.1" 302 0
[30/Oct/2020 22:15:36] code 400, message Bad request syntax ('\x05\x01\x00')
[30/Oct/2020 22:15:36] " " 400 -
[30/Oct/2020 22:15:36] code 400, message Bad request syntax ('\x04\x01\x00PpTi4\x00')
[30/Oct/2020 22:15:36] " PpTi4 " 400 -
[30/Oct/2020 22:53:22] code 400, message Bad request syntax ('\x00\x00\x00TZ\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x04\x010I\x00\x00\x00\x00\x80\x0b¨À\x00\x0c)t F\x07\x00tsXrcsXYs9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00bbXcsXctst\x00\x00\x00\x00\x00\x00')
[30/Oct/2020 22:53:22] "   TZ          0I    ¨À )t F tsXrcsXYs9                      bbXcsXctst      " 400 -
[30/Oct/2020 22:53:23] "GET / HTTP/1.1" 302 0
[30/Oct/2020 22:53:23] "GET /login/ HTTP/1.1" 200 2106
[30/Oct/2020 22:53:23] "GET /static/images/njit.png HTTP/1.1" 200 29837
[31/Oct/2020 00:21:54] "GET / HTTP/1.0" 302 0
[31/Oct/2020 00:21:54] "GET /login/ HTTP/1.0" 200 2106
[31/Oct/2020 01:49:43] "GET / HTTP/1.0" 302 0
[31/Oct/2020 01:49:43] "GET /login/ HTTP/1.0" 200 2106
[31/Oct/2020 03:56:43] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 07:35:51] "GET / HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:00] "GET http://49.234.67.30:8000/index/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:00] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:00] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:00] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:00] "GET http://49.234.67.30:8000/index/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:00] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:00] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:00] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:00] "GET http://49.234.67.30:8000/index/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:00] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:00] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:00] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/index/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/index/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/index/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/index/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/index/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/index/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/index/ HTTP/1.1" 302 0
Performing system checks...

<pymysql.connections.Connection object at 0x7f4902675b00>
System check identified no issues (0 silenced).

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
October 30, 2020 - 07:55:19
Django version 2.1.8, using settings 'mysite.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
cai正在进行登录。。。
admin正在进行登录。。。
admin正在进行登录。。。
admin正在进行登录。。。
admin正在进行登录。。。
admin正在进行登录。。。
正在进行登录。。。
cai正在进行登录。。。
cai正在进行登录。。。
----------------------------------------
Exception happened during processing of request from ('80.82.70.187', 41686)
----------------------------------------
admin正在进行登录。。。
select * from class where id = 2011513
select * from class where id = 2011514
select * from class where id = 2081501
select * from behavior where id = 1
admin正在进行登录。。。
admin正在进行登录。。。
----------------------------------------
Exception happened during processing of request from ('49.79.171.72', 20867)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('49.79.171.72', 20869)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('49.79.171.72', 20865)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.251.242.238', 46812)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('80.82.70.187', 58147)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('80.82.70.187', 52236)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('45.227.255.233', 61000)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 49193)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 49246)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 49282)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 49318)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 56727)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 56766)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 56796)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 56837)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 56989)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 57030)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 57069)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 57100)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 49957)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 49992)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 50028)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 50061)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 50181)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 50222)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 50259)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 50287)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 50392)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 50421)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 50449)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 50475)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 57810)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 57834)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 57858)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 57881)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 57955)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 57979)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 58001)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 58028)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 50875)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 50902)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 50938)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('58.247.212.239', 50962)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 58329)Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 09:30:01] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 10:10:12] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:47] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:47] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:47] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:47] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:48] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:48] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:48] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:48] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0

----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 58366)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 58404)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.89.19.140', 58432)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63160)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63176)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63192)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63210)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63281)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63298)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63323)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63337)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63405)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63428)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63450)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63464)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63535)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63554)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63570)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63597)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63665)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63679)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63694)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63714)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63772)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63795)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63811)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 63840)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('116.128.128.41', 53766)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('116.128.128.41', 53774)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('116.128.128.41', 53785)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('116.128.128.41', 53795)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('116.128.128.41', 53843)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('116.128.128.41', 53852)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('116.128.128.41', 53862)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('116.128.128.41', 53867)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('116.128.128.41', 53902)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('116.128.128.41', 53917)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('116.128.128.41', 53926)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('116.128.128.41', 53938)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 64305)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 64329)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 64348)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('183.192.179.16', 64370)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('182.254.52.17', 62932)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('182.254.52.17', 63344)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('182.254.52.17', 63818)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('182.254.52.17', 64240)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('182.254.52.17', 64789)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('182.254.52.17', 65094)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('182.254.52.17', 65500)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('182.254.52.17', 33054)Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:48] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:48] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:48] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:49] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:49] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:49] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:49] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:49] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:49] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:50] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:50] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:50] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:50] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:50] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:50] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:50] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:51] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:51] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:51] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:51] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:51] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:51] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:51] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:51] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:52] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:52] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:52] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:09:52] "GET http://49.234.67.30:8000/login/ HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 11:32:26] "GET / HTTP/1.0" 302 0
[31/Oct/2020 11:32:26] "GET /login/ HTTP/1.0" 200 2106
[31/Oct/2020 11:57:16] "GET / HTTP/1.0" 302 0
[31/Oct/2020 11:57:16] "GET /login/ HTTP/1.0" 200 2106
[31/Oct/2020 12:02:04] code 400, message Bad request version ('À\x14À')
[31/Oct/2020 12:02:04] You're accessing the development server over HTTPS, but it only supports HTTP.

[31/Oct/2020 13:33:14] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 22:06:01] "GET / HTTP/1.0" 302 0
[31/Oct/2020 22:06:01] "GET /login/ HTTP/1.0" 200 2106
[31/Oct/2020 22:14:00] "GET /index/ HTTP/1.1" 302 0
[31/Oct/2020 22:14:00] "GET /login/ HTTP/1.1" 200 2106
[31/Oct/2020 22:14:01] "GET /static/humane/humane.js HTTP/1.1" 304 0
[31/Oct/2020 22:14:01] "GET /static/humane/themes/original.css HTTP/1.1" 304 0
[31/Oct/2020 22:14:01] "GET /static/css/login.css HTTP/1.1" 304 0
[31/Oct/2020 22:14:01] "GET /static/images/logo.png HTTP/1.1" 304 0
[31/Oct/2020 22:14:01] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 304 0
[31/Oct/2020 22:14:01] "GET /static/images/login-bg.jpg HTTP/1.1" 304 0
[31/Oct/2020 22:34:53] "GET / HTTP/1.0" 302 0
[31/Oct/2020 22:34:54] "GET /login/ HTTP/1.0" 200 2106
[31/Oct/2020 23:10:08] "HEAD / HTTP/1.0" 302 0
[31/Oct/2020 23:16:30] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[31/Oct/2020 23:27:23] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[31/Oct/2020 23:27:23] "  /*à     Cookie: mstshash=Administr" 400 -
[01/Nov/2020 04:15:20] "HEAD / HTTP/1.0" 302 0
[01/Nov/2020 08:14:23] "GET / HTTP/1.0" 302 0
[01/Nov/2020 08:14:24] "GET /login/ HTTP/1.0" 200 2106
[01/Nov/2020 09:33:43] "GET / HTTP/1.0" 302 0
[01/Nov/2020 09:33:44] "GET /login/ HTTP/1.0" 200 2106
[01/Nov/2020 10:43:17] "HEAD / HTTP/1.0" 302 0
[01/Nov/2020 12:36:46] code 400, message Bad request version ('À\x14À')
[01/Nov/2020 12:36:46] You're accessing the development server over HTTPS, but it only supports HTTP.

[01/Nov/2020 13:05:14] "GET / HTTP/1.1" 302 0
[01/Nov/2020 14:25:50] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[01/Nov/2020 14:25:50] "  /*à     Cookie: mstshash=Administr" 400 -
[01/Nov/2020 15:18:54] "HEAD / HTTP/1.0" 302 0
[01/Nov/2020 18:22:34] "GET / HTTP/1.0" 302 0
[01/Nov/2020 18:22:36] "GET /login/ HTTP/1.0" 200 2106
[01/Nov/2020 18:38:18] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 302 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[01/Nov/2020 20:51:56] "GET / HTTP/1.0" 302 0
[01/Nov/2020 20:51:56] "GET /login/ HTTP/1.0" 200 2106
[01/Nov/2020 21:33:32] code 400, message Bad request syntax ('\x00\x00\x00TZ\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x04\x010I\x00\x00\x00\x00\x80\x0b¨À\x00\x0c)t F\x07\x00tsXrcsXYs9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00bbXcsXctst\x00\x00\x00\x00\x00\x00')
[01/Nov/2020 21:33:32] "   TZ          0I    ¨À )t F tsXrcsXYs9                      bbXcsXctst      " 400 -
[01/Nov/2020 21:33:32] "GET / HTTP/1.1" 302 0
[01/Nov/2020 21:33:32] "GET /login/ HTTP/1.1" 200 2106
[01/Nov/2020 21:33:32] "GET /static/images/njit.png HTTP/1.1" 200 29837
[01/Nov/2020 23:48:01] "GET / HTTP/1.1" 302 0
[02/Nov/2020 00:38:16] "GET /index/ HTTP/1.1" 302 0
[02/Nov/2020 00:38:16] "GET /login/ HTTP/1.1" 200 2106
[02/Nov/2020 00:38:17] "GET /static/humane/themes/original.css HTTP/1.1" 304 0
[02/Nov/2020 00:38:17] "GET /static/humane/humane.js HTTP/1.1" 304 0
[02/Nov/2020 00:38:17] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 304 0
[02/Nov/2020 00:38:17] "GET /static/css/login.css HTTP/1.1" 304 0
[02/Nov/2020 00:38:17] "GET /static/images/logo.png HTTP/1.1" 200 199830
[02/Nov/2020 00:38:17] "GET /static/images/login-bg.jpg HTTP/1.1" 304 0
[02/Nov/2020 00:59:10] "GET / HTTP/1.1" 302 0
[02/Nov/2020 01:58:04] "GET /index/ HTTP/1.1" 302 0
[02/Nov/2020 01:58:04] "GET /login/ HTTP/1.1" 200 2106
[02/Nov/2020 01:58:04] "GET /static/humane/themes/original.css HTTP/1.1" 200 1480
[02/Nov/2020 01:58:04] "GET /static/humane/humane.js HTTP/1.1" 200 7078
[02/Nov/2020 01:58:04] "GET /static/css/login.css HTTP/1.1" 200 3789
[02/Nov/2020 01:58:04] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 200 92632
[02/Nov/2020 01:58:04] "GET /static/images/logo.png HTTP/1.1" 200 199830
[02/Nov/2020 01:58:05] "GET /static/images/njit.png HTTP/1.1" 200 29837
[02/Nov/2020 01:58:08] "GET /static/images/login-bg.jpg HTTP/1.1" 200 413554
[02/Nov/2020 02:17:27] "GET /index/ HTTP/1.1" 302 0
[02/Nov/2020 02:17:28] "GET /login/ HTTP/1.1" 200 2106
[02/Nov/2020 02:17:28] "GET /static/humane/themes/original.css HTTP/1.1" 200 1480
[02/Nov/2020 02:17:50] "GET /login/ HTTP/1.1" 200 2106
[02/Nov/2020 02:17:51] "GET /static/humane/themes/original.css HTTP/1.1" 200 1480
[02/Nov/2020 02:17:51] "GET /static/humane/humane.js HTTP/1.1" 200 7078
[02/Nov/2020 02:17:51] "GET /static/css/login.css HTTP/1.1" 200 3789
[02/Nov/2020 02:17:51] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 200 92632
[02/Nov/2020 02:17:51] "GET /static/images/njit.png HTTP/1.1" 200 29837
[02/Nov/2020 02:17:53] "GET /static/images/logo.png HTTP/1.1" 200 199830
[02/Nov/2020 02:17:55] "GET /static/images/login-bg.jpg HTTP/1.1" 200 311698
[02/Nov/2020 02:27:20] "GET /login/ HTTP/1.1" 200 2106
[02/Nov/2020 02:27:20] "GET /static/humane/humane.js HTTP/1.1" 200 7078
[02/Nov/2020 02:27:20] "GET /static/js/jquery-1.9.1.min.js HTTP/1.1" 200 90112
Internal Server Error: /index/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 705, in _write_bytes
    self._sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/local/PythonTest/mysite/mysite/view.py", line 75, in index
    cur.execute(adminSql)
  File "/usr/local/lib/python3.5/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 504, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 763, in _execute_command
    self._write_bytes(packet)
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 710, in _write_bytes
    "MySQL server has gone away (%r)" % (e,))
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
[02/Nov/2020 02:27:38] "POST /index/ HTTP/1.1" 500 88212
[02/Nov/2020 02:27:38] "GET /favicon.ico HTTP/1.1" 302 0
Internal Server Error: /index/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/local/PythonTest/mysite/mysite/view.py", line 75, in index
    cur.execute(adminSql)
  File "/usr/local/lib/python3.5/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 504, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 742, in _execute_command
    raise err.InterfaceError(0, '')
pymysql.err.InterfaceError: (0, '')
[02/Nov/2020 02:28:04] "POST /index/ HTTP/1.1" 500 79260
[02/Nov/2020 02:31:40] "GET /index/ HTTP/1.1" 302 0
[02/Nov/2020 02:31:40] "GET /login/ HTTP/1.1" 200 2106
[02/Nov/2020 02:31:40] "GET /static/images/logo.png HTTP/1.1" 200 90112
Internal Server Error: /index/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/local/PythonTest/mysite/mysite/view.py", line 75, in index
    cur.execute(adminSql)
  File "/usr/local/lib/python3.5/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 504, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 742, in _execute_command
    raise err.InterfaceError(0, '')
pymysql.err.InterfaceError: (0, '')
[02/Nov/2020 02:31:46] "POST /index/ HTTP/1.1" 500 79260
[02/Nov/2020 02:31:46] "GET /favicon.ico HTTP/1.1" 302 0
